### ISSUE TITLE
Support for multiple databases & Database name specification at runtime

### ISSUE THREAD

**Issue by philippefutureboy** [statsbotco/cube.js#79]
**Is your feature request related to a problem? Please describe.**
We provide analytics to healthcare professionals. Due to the sensitive nature of our clients' data, we have opted to separate each of our clients' data into separate database schemas. Unfortunately, even though all of our schemas have the same structure, Cube.js's single-database model prevents us from using Cube.js as an analytics engine on top of our data warehouses. 

**Describe the solution you'd like**
Add the ability to specify multiple data sources in the configuration of the Cube.js service, and add the ability to specify which database schema to use at query time.

**Suggested implementation**

1. Due to the flat structure of .env files, it would be hard to specify multiple databases without custom names. Instead, it is proposed to use `yaml` environment files with the following structure:

```yaml
 api_secret: secret
 dbs: 
   - alias: <YOUR_DB_ALIAS_NAME>
      host: <YOUR_DB_HOST_HERE>
      name: <YOUR_DB_NAME_HERE>
      user: <YOUR_DB_USER_HERE>
      password: <YOUR_DB_PASS_HERE>
      type: postgres
```

Here alias serves for easier identification for the step 3.

2. If host, name, type & user are the same for any two dbs, group these dbs into a singular connection. Otherwise deploy one connection per individual database.

3. At query time, allow the use of the alias specified in step 1 to specify the database to interact with.

```js
{
  database: '<YOUR_DB_ALIAS_HERE>'
  measures: ['Stories.count'],
  dimensions: ['Stories.category'],
  filters: [{
    dimension: 'Stories.isDraft',
    operator: 'equals',
    values: ['No']
  }],
  timeDimensions: [{
    dimension: 'Stories.time',
    dateRange: ['2015-01-01', '2015-12-31'],
    granularity: 'month'
  }],
  limit: 100
}
```

which would translate to picking the right connection + adding a USE database statement:

```sql
USE '<YOUR_DB_ALIAS_HERE>';

-- SQL equivalent query
```

4. (Optional): The next natural evolution of this idea is to allow to define multiple Cube.js schema and assign them to different database aliases.
```js
// single database setup
cube(`Users`, {
  sql: `SELECT * FROM users`
});

// multiple database setup
cube(`<YOUR_DB_ALIAS_HERE>`, `Users`, {
  sql: `SELECT * FROM users`
});
```

**Describe alternatives you've considered**
Create one Cube.js serverless deployment per database schema (which means managing 10s-100s of deployments) + HIPAA compliance requires us to have our PHI data within a VPC thereby greatly reducing the performance of lambdas due to the extended warming up period. 

I know this may seem like a niche use case at first, but I'm sure that the valid use-cases will grow along as you get to encounter more situations. This feature essentially federates all of these different database APIs into a single server, a bit a la GraphQL.

Let me know what you think :)

Have a great day ☀️ 

Cheers,

Philippe

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Thanks for posting this! 🙌 Really detailed description!

Actually multi-tenancy support is already in development. I'm curious is one analytical user can access 2 different databases simultaneously in your case or is it just one DB that belongs to this user?

**Comment by philippefutureboy** [comment]
🙌 

@paveltiunov Thanks for your answer!
Glad to hear that something is in progress :D

For the moment we do not have queries that span across multiple tenants, but it's part of our near-to-medium term roadmap.

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! So we're going to release this stuff next week.

API will be something like:

```
CubejsServerCore.create({
  multiTenantAppId: ({ authInfo }) => authInfo.appId, // will be used as caching key for various in-memory structures like schema compilation results, connection pool, etc.
  repositoryFactory: ({ authInfo }) => new FileRepository(`schema/${authInfo.appId}`),
  driverFactory: ({ authInfo }) => new PostgresDriver({ dbName: `db_${authInfo.appId}`})
})
```

Do you think it fits your case? Also are you going to deploy it to AWS Lambda?

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! We just released it in v0.7.0. Please let me know if this approach works for you.

**Comment by philippefutureboy** [comment]
@paveltiunov Thanks for your good work! Sorry, I didn't get notified when you answered! Just saw your answer and decided to give it a try :D

Before trying to do multi-tenant, I first attempted to boot `@cubejs-backend/serverless-aws` with the default codebase. 

While I was successful at deploying the serverless setup I wasn't able to connect to it via the `@cubejs-client/core`. When I call the `cubejsApi.load` method as per the [docs](https://cube.dev/docs/frontend-introduction), I receive a 404 for `https://<my-api-gtw>.execute-api.ca-central-1.amazonaws.com/dev/load`.

Similarly, I had a 404 error when testing the function `/{proxy}` directly from the AWS Console for the API Gateway in question and providing `load` as the `{proxy}` URL parameter.

Here's the serverless config:

```
service: cubesls-test

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-express

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage}
  region: "ca-central-1"
  profile: serverless
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        - "*"
  vpc:
    id: ${file(./serverless.env.yml):${self:provider.stage}.AWS_VPC_ID}
    securityGroupIds:
      - ${file(./serverless.env.yml):${self:provider.stage}.AWS_SG1_ID}
    subnetIds:
      - ${file(./serverless.env.yml):${self:provider.stage}.AWS_SN1_ID}
      - ${file(./serverless.env.yml):${self:provider.stage}.AWS_SN2_ID}
    role: ${file(./serverless.env.yml):${self:provider.stage}.AWS_SN2_ID}
  environment:
    CUBEJS_API_SECRET: ${file(./serverless.env.yml):${self:provider.stage}.CUBEJS_API_SECRET}
    CUBEJS_APP: "${self:service.name}-${self:provider.stage}"
    CUBEJS_DB_HOST: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_HOST}
    CUBEJS_DB_PORT: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_PORT}
    CUBEJS_DB_NAME: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_DB_NAME}
    CUBEJS_DB_TYPE: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_TYPE}
    CUBEJS_DB_USER: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_USER}
    CUBEJS_DB_PASS: ${file(./serverless.env.yml):${self:provider.stage}.AWS_RDS_PASSWORD}
    REDIS_URL:  ${file(./serverless.env.yml):${self:provider.stage}.AWS_REDIS_URL}
    NODE_ENV: "${file(./serverless.env.yml):${self:provider.stage}.NODE_ENV}"
    CUBEJS_API_URL:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: "ApiGatewayRestApi"
          - ".execute-api."
          - Ref: "AWS::Region"
          - ".amazonaws.com/${self:provider.stage}"
    AWS_ACCOUNT_ID:
      Fn::Join:
        - ""
        - - Ref: "AWS::AccountId"

functions:
  cubejs:
    handler: cube.api
    timeout: 30
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: ANY
  cubejsProcess:
    handler: cube.process
    timeout: 630
    events:
      - sns: "${self:service.name}-${self:provider.stage}-process"
 ```
The said configuration comes from the default configuration generated by the serverless template (as per [this guide](https://cube.dev/docs/deployment#serverless).

Any idea what could be the issue here?

Meanwhile I'll attempt to boot the backend/server version of cubejs :)

Have a great day/weekend! ☀️

Cheers,

Phil

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Thanks for feedback! Could you please share your AWS Lambda logs?

**Comment by philippefutureboy** [comment]
Yes, no problem :)

`Streams for /aws/lambda/cubesls-test-dev-cubejs`

```
START RequestId: 7454023d-0418-48ba-8c35-55af3022dc45 Version: $LATEST
2019-05-31T17:07:44.262Z	7454023d-0418-48ba-8c35-55af3022dc45	🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
2019-05-31T17:07:44.262Z	7454023d-0418-48ba-8c35-55af3022dc45	🦅 Dev environment available at https://<my-api-gtw>.execute-api.ca-central-1.amazonaws.com/dev
END RequestId: 7454023d-0418-48ba-8c35-55af3022dc45
REPORT RequestId: 7454023d-0418-48ba-8c35-55af3022dc45	Duration: 148.92 ms	Billed Duration: 200 ms Memory Size: 1024 MB	Max Memory Used: 111 MB
	
START RequestId: 40fa6ff7-4aa7-4948-a8c4-26d1578d5182 Version: $LATEST
END RequestId: 40fa6ff7-4aa7-4948-a8c4-26d1578d5182
REPORT RequestId: 40fa6ff7-4aa7-4948-a8c4-26d1578d5182	Duration: 40.42 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 111 MB
	
START RequestId: 5d9be7cb-b330-4673-977b-8fa9cabeb91f Version: $LATEST
END RequestId: 5d9be7cb-b330-4673-977b-8fa9cabeb91f
REPORT RequestId: 5d9be7cb-b330-4673-977b-8fa9cabeb91f	Duration: 138.33 ms	Billed Duration: 200 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
	
START RequestId: bbd9f47a-7d8f-440f-b5d8-957012fd625a Version: $LATEST
END RequestId: bbd9f47a-7d8f-440f-b5d8-957012fd625a
REPORT RequestId: bbd9f47a-7d8f-440f-b5d8-957012fd625a	Duration: 2.64 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
	
START RequestId: 0a366d5d-83a8-43f2-941e-d2ea4787812b Version: $LATEST
END RequestId: 0a366d5d-83a8-43f2-941e-d2ea4787812b
REPORT RequestId: 0a366d5d-83a8-43f2-941e-d2ea4787812b	Duration: 110.26 ms	Billed Duration: 200 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
	
START RequestId: 6f375c16-653f-4a54-8b52-1aac971670ea Version: $LATEST
END RequestId: 6f375c16-653f-4a54-8b52-1aac971670ea
REPORT RequestId: 6f375c16-653f-4a54-8b52-1aac971670ea	Duration: 4.28 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
	
START RequestId: cce6455b-cfe5-4d72-be39-a937f0411183 Version: $LATEST
END RequestId: cce6455b-cfe5-4d72-be39-a937f0411183
REPORT RequestId: cce6455b-cfe5-4d72-be39-a937f0411183	Duration: 2.02 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
	
START RequestId: 39474dc4-2745-4453-a29e-7e6055698337 Version: $LATEST
END RequestId: 39474dc4-2745-4453-a29e-7e6055698337
REPORT RequestId: 39474dc4-2745-4453-a29e-7e6055698337	Duration: 1.90 ms	Billed Duration: 100 ms Memory Size: 1024 MB	Max Memory Used: 118 MB
```

`Streams for /aws/lambda/cubesls-test-dev-cubejsProcess`

<Empty>


Nothing noteworthy tbh :/

**Comment by paveltiunov** [comment]
@philippefutureboy Ah. Yep. Gotcha. It's because actual endpoint path is `https://<my-api-gtw>.execute-api.ca-central-1.amazonaws.com/dev/cubejs-api/v1/load`. Could you please try and let me know if it works for you?

**Comment by philippefutureboy** [comment]
Hey @paveltiunov !

I successfully connected to the cube-js backend using the URL provided above. However, my redis server was inaccessible to the lambdas, which resulted in the lambda timing out. Unfortunately, the redis connection errors didn't log any error.
I think it would be really helpful to let the user know via logs if there are any connection issues with either the database or the redis server :)

Once my redis became accessible, I was able to connect to the backend via the frontend, and didn't suffer any timeouts. However, the client kept re-issuing the query again and again, and didn't resolve to anything by the time I stopped it after a minute. To be noted that the lambdas sent their response before their timeout (5 seconds vs 30 seconds).

By looking at the response of previously issued queries, I got either a 200 with empty body or 200 with `{"error":"Continue wait","stage":{"stage":"#1 in queue"}}`. Based on the [docs](https://cube.dev/docs/rest-api), "Continue wait"s are due to a busy database or a long query. I find either to be unlikely. The database to which Cube.js connects is the dev database and the logs indicate that the database had only 2 connections and used very little CPU/RAM throughout the CubeJS load. As for the long query, I've been using the base query provided by the template, so I wouldn't expect the query to take very long.

Does CubeJS keep the connection & queries in memory between each API call?

Here are some sample logs:

```
START RequestId: edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e Version: $LATEST
2019-06-03T16:26:14.647Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Load Request:
{
    "query": "{\"measures\":[\"Orders.count\"],\"dimensions\":[\"Orders.status\"]}",
    "authInfo": {
        "iat": 1559484780,
        "exp": 1562076780
    }
}

2019-06-03T16:26:14.653Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Query started:
{
    "query": "SELECT orders.status `orders.status`, count(*) `orders.count` FROM ( select 1 as id, 100 as amount, 'new' status UNION ALL select 2 as id, 200 as amount, 'new' status UNION ALL select 3 as id, 300 as amount, 'processed' status UNION ALL select 4 as id, 500 as amount, 'processed' status UNION ALL select 5 as id, 600 as amount, 'shipped' status ) AS orders GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
    "params": []
}

2019-06-03T16:26:14.663Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Missing cache for:
{
    "cacheKey": [
        "SELECT\n      orders.status `orders.status`, count(*) `orders.count`\n    FROM\n      (\n  select 1 as id, 100 as amount, 'new' status\n  UNION ALL\n  select 2 as id, 200 as amount, 'new' status\n  UNION ALL\n  select 3 as id, 300 as amount, 'processed' status\n  UNION ALL\n  select 4 as id, 500 as amount, 'processed' status\n  UNION ALL\n  select 5 as id, 600 as amount, 'shipped' status\n  ) AS orders\n  GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
        [],
        []
    ]
}

2019-06-03T16:26:14.664Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Missing cache for:
{
    "cacheKey": [
        "select count(*) from (\n  select 1 as id, 100 as amount, 'new' status\n  UNION ALL\n  select 2 as id, 200 as amount, 'new' status\n  UNION ALL\n  select 3 as id, 300 as amount, 'processed' status\n  UNION ALL\n  select 4 as id, 500 as amount, 'processed' status\n  UNION ALL\n  select 5 as id, 600 as amount, 'shipped' status\n  ) AS orders",
        []
    ]
}

2019-06-03T16:26:19.658Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Continue wait:
{
    "duration": 5006,
    "query": "SELECT orders.status `orders.status`, count(*) `orders.count` FROM ( select 1 as id, 100 as amount, 'new' status UNION ALL select 2 as id, 200 as amount, 'new' status UNION ALL select 3 as id, 300 as amount, 'processed' status UNION ALL select 4 as id, 500 as amount, 'processed' status UNION ALL select 5 as id, 600 as amount, 'shipped' status ) AS orders GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
    "params": []
}

2019-06-03T16:26:19.666Z	edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Continue wait:
{
    "query": "{\"measures\":[\"Orders.count\"],\"dimensions\":[\"Orders.status\"]}",
    "authInfo": {
        "iat": 1559484780,
        "exp": 1562076780
    }
}

END RequestId: edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e
REPORT RequestId: edaf35c2-c0f3-4cdc-8e43-5c5803a58a6e	Duration: 5022.90 ms	Billed Duration: 5100 ms Memory Size: 1024 MB	Max Memory Used: 107 MB	
START RequestId: 823ac54a-5235-4bad-8b48-0787be693f1a Version: $LATEST
2019-06-03T16:26:19.775Z	823ac54a-5235-4bad-8b48-0787be693f1a	Load Request:
{
    "query": "{\"measures\":[\"Orders.count\"],\"dimensions\":[\"Orders.status\"]}",
    "authInfo": {
        "iat": 1559484780,
        "exp": 1562076780
    }
}

2019-06-03T16:26:19.783Z	823ac54a-5235-4bad-8b48-0787be693f1a	Query started:
{
    "query": "SELECT orders.status `orders.status`, count(*) `orders.count` FROM ( select 1 as id, 100 as amount, 'new' status UNION ALL select 2 as id, 200 as amount, 'new' status UNION ALL select 3 as id, 300 as amount, 'processed' status UNION ALL select 4 as id, 500 as amount, 'processed' status UNION ALL select 5 as id, 600 as amount, 'shipped' status ) AS orders GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
    "params": []
}

2019-06-03T16:26:19.784Z	823ac54a-5235-4bad-8b48-0787be693f1a	Missing cache for:
{
    "cacheKey": [
        "SELECT\n      orders.status `orders.status`, count(*) `orders.count`\n    FROM\n      (\n  select 1 as id, 100 as amount, 'new' status\n  UNION ALL\n  select 2 as id, 200 as amount, 'new' status\n  UNION ALL\n  select 3 as id, 300 as amount, 'processed' status\n  UNION ALL\n  select 4 as id, 500 as amount, 'processed' status\n  UNION ALL\n  select 5 as id, 600 as amount, 'shipped' status\n  ) AS orders\n  GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
        [],
        []
    ]
}

2019-06-03T16:26:19.785Z	823ac54a-5235-4bad-8b48-0787be693f1a	Missing cache for:
{
    "cacheKey": [
        "select count(*) from (\n  select 1 as id, 100 as amount, 'new' status\n  UNION ALL\n  select 2 as id, 200 as amount, 'new' status\n  UNION ALL\n  select 3 as id, 300 as amount, 'processed' status\n  UNION ALL\n  select 4 as id, 500 as amount, 'processed' status\n  UNION ALL\n  select 5 as id, 600 as amount, 'shipped' status\n  ) AS orders",
        []
    ]
}

2019-06-03T16:26:24.789Z	823ac54a-5235-4bad-8b48-0787be693f1a	Continue wait:
{
    "duration": 5006,
    "query": "SELECT orders.status `orders.status`, count(*) `orders.count` FROM ( select 1 as id, 100 as amount, 'new' status UNION ALL select 2 as id, 200 as amount, 'new' status UNION ALL select 3 as id, 300 as amount, 'processed' status UNION ALL select 4 as id, 500 as amount, 'processed' status UNION ALL select 5 as id, 600 as amount, 'shipped' status ) AS orders GROUP BY 1 ORDER BY 2 DESC LIMIT 10000",
    "params": []
}

2019-06-03T16:26:24.797Z	823ac54a-5235-4bad-8b48-0787be693f1a	Continue wait:
{
    "query": "{\"measures\":[\"Orders.count\"],\"dimensions\":[\"Orders.status\"]}",
    "authInfo": {
        "iat": 1559484780,
        "exp": 1562076780
    }
}

END RequestId: 823ac54a-5235-4bad-8b48-0787be693f1a
REPORT RequestId: 823ac54a-5235-4bad-8b48-0787be693f1a	Duration: 5026.98 ms	Billed Duration: 5100 ms Memory Size: 1024 MB	Max Memory Used: 107 MB	
START RequestId: 283877de-64d5-4cab-ac3b-5052ce2b08b1 Version: $LATEST
...
```

Any idea what may be causing this issue?

**Comment by philippefutureboy** [comment]
I dove in the logs of the database provided by RDS, and I found the following:

```
2019-06-02T17:03:39.268218Z 108525 [Note] Aborted connection 108525 to db: 'db_name' user: 'user' host: '10.50.0.95' (Got an error reading communication packets)
2019-06-02T17:05:11.684771Z 108526 [Note] Aborted connection 108526 to db: 'db_name' user: 'user' host: '10.50.0.95' (Got an error reading communication packets)
2019-06-02T17:07:00.643361Z 108527 [Note] Aborted connection 108527 to db: 'db_name' user: 'user' host: '10.50.0.95' (Got an error reading communication packets)
2019-06-02T17:10:24.523446Z 108529 [Note] Aborted connection 108529 to db: 'db_name' user: 'user' host: '10.50.0.95' (Got an error reading communication packets)
2019-06-02T17:17:37.871285Z 108531 [Warning] IP address '10.50.1.197' could not be resolved: Name or service not known
2019-06-02T17:17:37.889395Z 108531 [Note] Aborted connection 108531 to db: 'db_name' user: 'user' host: '10.50.1.197' (Got an error reading communication packets)
2019-06-02T17:19:32.652677Z 108533 [Note] Aborted connection 108533 to db: 'db_name' user: 'user' host: '10.50.1.197' (Got an error reading communication packets)
```

Is this something you have ever encountered with CubeJS?

I attempted connecting to the database with the same configuration through a small connectivity test lambda I wrote, and I am able to issue queries without problem.

Here's the lambda code if that can help:

```
const mysql = require('mysql');
const redis = require('redis');
const Promise = require('bluebird');

exports.handler = function handler (event, context) {
  const mysqlOptions = {
    host: process.env.CUBEJS_DB_HOST,
    port: process.env.CUBEJS_DB_PORT,
    database: process.env.CUBEJS_DB_NAME,
    user: process.env.CUBEJS_DB_USER,
    password: process.env.CUBEJS_DB_PASS,
  };
  const redisUrl = process.env.REDIS_URL;
  return Promise.all([
    testMySQLConnection(mysqlOptions),
    testRedisConnection(redisUrl)
  ]).then(() => {
    console.log('success');
  }).catch((err) => {
    console.error(err);
  });
};

function testMySQLConnection(options) {
  var connection = mysql.createConnection(options);
  return new Promise((resolve, reject) => {
    connection.connect(function (err) {
      if (err) reject(err);
      resolve(connection);
    });
  }).timeout(2000)
    .then((connection) => {
      return new Promise((resolve, reject) => {
        connection.query('SELECT 111 + 111 AS result;', (err, res) => {
          if (err) {
            reject(err);
          } else {
            console.log(`successful mysql connection established with host ${options.host}`);
            console.log('result', res);
            connection.destroy();
            resolve();
          }
        });
      });
    })
    .catch(Promise.TimeoutError, () => {
      throw new Error(`mysql connection to ${options.host} timed out`)
    })
    .catch((e) => {
      const err = new Error(`mysql connection to ${options.host} failed with error ${e.message})`);
      err.stack = e.stack;
      throw err;
    });
}

function testRedisConnection(redisUrl) {
  var client;
  return new Promise((resolve, reject) => {
    client = redis.createClient({
      url: redisUrl,
      connect_timeout: 1500,
      retry_strategy: function (options) {
        if (options.error) {
          return options.error;
        }
        return undefined;
      }
    });
    client.on('error', (e) => {
      const err = new Error(`redis connection to ${redisUrl} failed with error ${e.message})`);
      err.stack = e.stack;
      err.errno = e.errno;
      err.code = e.code;
      reject(err);
    });
    client.on('connect', () => {
      console.error(`redis connection to ${redisUrl} established`)
      resolve();
    });
  }).timeout(2000)
  .then(() => {
    return new Promise((resolve, reject) => {
      client.set("string key", "string val", (err, res) => {
        if (err) {
          console.error(`redis 'set' operation failed with error ${err.message}`)
          reject(err);
        } else {
          resolve();
        }
      });
    });
  }).then(() => {
    return new Promise((resolve, reject) => {
      client.get("string key", (err, res) => {
        if (err) {
          console.error(`redis 'get' operation failed with error ${err.message}`)
          reject(err);
        } else {
          console.log('get operation result', { "string key": res });
          resolve();
        }
      });
    });
  }).then(() => {
    console.log(`successful redis connection with ${redisUrl} established. Operations successful.`);
  }).catch(Promise.TimeoutError, (e) => {
    console.error(`redis connection to ${redisUrl} timed out`);
    throw e;
  }).finally(() => {
    console.log('closing redis connection');
    client.quit();
  });
}
```

**Comment by paveltiunov** [comment]
@philippefutureboy Hey Philippe! Interesting. Could you please post your `cubejsProcess` logs? It's separate lambda for processing actual db queries.

**Comment by philippefutureboy** [comment]
@paveltiunov There's nothing there - "No Log Streams To Show" 😵

The only thing that can come to mind is inappropriate access to call the cubeProcess lambda, so here's the iamRoleStatements part of the serverless configuration:

```
iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        - "*"
```

Thanks again for your help 😉
